import"./a01-logtest.cy"
import"./a02-MenuApp.cy"
import"./a03-beneficiosApp.cy"
import"./a04-perfilApp.cy"
import"./a05-panelApp.cy"
import"./a06-cerrarApp.cy"
import"./a07notificacionesApp.cy"