import "./01-logtest.cy"
import "./02-Homepage.cy"
import "./03-sectores.cy"
import "./04-empresas.cy"
import "./05-EmpresaSecor.cy"
import "./16-altaybajanovedades.cy"
import "./07-novedad.cy"
import "./08-usuariosPage.cy"
import"./09-nuevoferiados.cy"
import "./10-visitas.cy"
import "./11-jornadasimple.cy"
import "./12-jornadamultiple.cy"
import "./13-calendarios.cy"
import "./06a-SistemastestEmpleados.cy"
import"./15-agregoeliminovaca.cy"
import"./17-vacaciones.cy"
import"./18-novedaddsdlincencias.cy"
import"./19-Asignovacacionylicencia.cy"
import"./20-aMarcacionsistemalenox.cy"
import"./22-preferencias.cy"
import"./25-Digitalfirma.cy"
import"./29-beneficiossistemas.cy"
import"./30-Estudios.cy"
//import"./26-reciboDeSueldo.cy"
import"./27-arraynuevo.cy"
//import"./99m-eliminoReciboDeSueldo.cy"
import"./99q-eliminomarcacion.cy"
import"./99o-eliminoEstudio.cy"
import"./99p-eliminobeneficio.cy"
import"./99l-eliminoFirmas.cy"
import"./99k-eliminojmultiple.cy"
import"./99j-EliminoVacaciones.cy"
import"./99i-eliminoCalendario.cy"
import"./99h-EliminoJornada.cy"
import"./99g-Eliminovisita.cy"
import"./99f-EliminoFeriado.cy"
import"./99e-EliminoUsuario.cy"
import"./99d-eliminoNovedad.cy"
import"./99c-elimino empleado.cy"
import"./99b-EliminoSector.cy"
import"./99a-BorramosEmpresa.cy"